language: ruby
rvm:
  - ruby-head
  - 3.0
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.0
bundler_args: --without guard:bundler:mutant:rubocop
